use konto_api::dto::account::*;
use konto_api::dto::auth::*;
use konto_api::dto::contact::*;
use konto_api::dto::document::*;
use konto_api::dto::exchange_rate::*;
use konto_api::dto::fiscal_year::*;
use konto_api::dto::import::*;
use konto_api::dto::journal::*;
use konto_api::dto::project::*;
use konto_api::dto::report::*;
use konto_api::dto::settings::*;
use konto_api::dto::template::*;
use konto_api::dto::time_entry::*;
use konto_api::dto::recurring_invoice::*;
use konto_api::dto::credit_note::*;
use konto_api::dto::invoice::CreateInvoiceFromTimeEntriesRequest;
use konto_api::dto::dashboard_charts::*;
use konto_api::dto::email_template::*;
use konto_api::dto::expense::*;
use konto_api::dto::dunning::*;
use konto_api::dto::bank_transaction::*;
use konto_api::dto::contact_tag::*;
use konto_api::dto::contact_person::*;
use konto_api::dto::vat_rate::*;
use konto_api::dto::currency::*;
use konto_api::dto::activity_type::*;
use konto_api::dto::invoice_payment::*;
use konto_api::dto::fixed_asset::*;
use konto_api::dto::employee::*;
use konto_api::dto::payroll_settings::*;
use konto_api::dto::payroll_run::*;
use konto_api::dto::payout_entry::*;
use konto_api::dto::project_budget::*;
use konto_api::dto::project_sub_status::*;
use konto_api::dto::project_member::*;
use konto_api::dto::project_activity_type::*;
use konto_api::dto::setup::*;
use konto_api::handlers::contact_sub_handler::DocumentSummaryResponse;
use konto_api::handlers::*;
use konto_core::services::lohnausweis_service::{LohnausweisData, EmployeeSummary};
// Note: LohnausweisData/EmployeeSummary are the internal Rust types (official Swiss form name)
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth_handler::login,
        auth_handler::refresh,
        auth_handler::me,
        auth_handler::update_my_profile,
        auth_handler::update_my_language,
        auth_handler::upload_my_avatar,
        account_handler::list_accounts,
        account_handler::create_account,
        account_handler::get_account,
        account_handler::update_account,
        account_handler::delete_account,
        account_handler::accounts_tree,
        contact_handler::list_contacts,
        contact_handler::create_contact,
        contact_handler::get_contact,
        contact_handler::update_contact,
        contact_handler::delete_contact,
        contact_person_handler::list_by_contact,
        contact_person_handler::create_person,
        contact_person_handler::update_person,
        contact_person_handler::delete_person,
        contact_tag_handler::list_tags,
        contact_tag_handler::create_tag,
        contact_tag_handler::delete_tag,
        contact_tag_handler::assign_tag_to_contact,
        contact_tag_handler::remove_tag_from_contact,
        contact_sub_handler::list_contact_invoices,
        contact_sub_handler::list_contact_documents,
        contact_sub_handler::list_contact_time_entries,
        journal_handler::list_journal,
        journal_handler::get_journal_entry,
        journal_handler::create_journal_entry,
        journal_handler::post_journal_entry,
        journal_handler::reverse_journal_entry,
        project_handler::list_projects,
        project_handler::create_project,
        project_handler::get_project,
        project_handler::update_project,
        project_handler::delete_project,
        project_handler::get_project_summary,
        time_entry_handler::list_time_entries,
        time_entry_handler::get_time_entry,
        time_entry_handler::create_time_entry,
        time_entry_handler::update_time_entry,
        time_entry_handler::delete_time_entry,
        fiscal_year_handler::list_fiscal_years,
        fiscal_year_handler::get_fiscal_year,
        fiscal_year_handler::create_fiscal_year,
        fiscal_year_handler::update_fiscal_year,
        fiscal_year_handler::close_fiscal_year,
        exchange_rate_handler::list_exchange_rates,
        exchange_rate_handler::get_latest_rate,
        exchange_rate_handler::get_exchange_rate,
        exchange_rate_handler::create_exchange_rate,
        exchange_rate_handler::update_exchange_rate,
        exchange_rate_handler::delete_exchange_rate,
        report_handler::trial_balance,
        report_handler::balance_sheet,
        report_handler::profit_loss,
        report_handler::account_ledger,
        report_handler::vat_report,
        report_handler::dashboard_stats,
        import_handler::upload_import,
        import_handler::preview_import,
        import_handler::execute_import,
        settings_handler::get_settings,
        settings_handler::update_settings,
        settings_handler::upload_logo,
        bank_account_handler::list_bank_accounts,
        bank_account_handler::create_bank_account,
        bank_account_handler::update_bank_account,
        bank_account_handler::delete_bank_account,
        template_handler::list_templates,
        template_handler::get_template,
        template_handler::create_template,
        template_handler::update_template,
        template_handler::delete_template,
        template_handler::duplicate_template,
        document_handler::list_documents,
        document_handler::get_document,
        document_handler::create_document,
        document_handler::update_document,
        document_handler::delete_document,
        document_handler::send_document,
        document_handler::accept_document,
        document_handler::reject_document,
        document_handler::convert_document,
        document_handler::get_document_pdf,
        recurring_invoice_handler::list_recurring_invoices,
        recurring_invoice_handler::get_recurring_invoice,
        recurring_invoice_handler::create_recurring_invoice,
        recurring_invoice_handler::update_recurring_invoice,
        recurring_invoice_handler::delete_recurring_invoice,
        recurring_invoice_handler::trigger_recurring_invoices,
        credit_note_handler::list_credit_notes,
        credit_note_handler::get_credit_note,
        credit_note_handler::create_credit_note,
        credit_note_handler::update_credit_note,
        credit_note_handler::delete_credit_note,
        credit_note_handler::issue_credit_note,
        credit_note_handler::apply_credit_note,
        credit_note_handler::cancel_credit_note,
        credit_note_handler::download_credit_note_pdf,
        dashboard_charts_handler::monthly_revenue,
        dashboard_charts_handler::monthly_expenses,
        dashboard_charts_handler::invoice_aging,
        dashboard_charts_handler::top_outstanding,
        dashboard_charts_handler::dashboard_overview,
        dashboard_charts_handler::cash_flow,
        dashboard_charts_handler::ar_aging,
        dashboard_charts_handler::ap_aging,
        email_template_handler::list_email_templates,
        email_template_handler::get_email_template,
        email_template_handler::update_email_template,
        email_template_handler::preview_email_template,
        expense_handler::list_expenses,
        expense_handler::get_expense,
        expense_handler::create_expense,
        expense_handler::update_expense,
        expense_handler::delete_expense,
        expense_handler::approve_expense,
        expense_handler::pay_expense,
        expense_handler::cancel_expense,
        expense_handler::upload_receipt,
        expense_category_handler::list_expense_categories,
        expense_category_handler::create_expense_category,
        expense_category_handler::update_expense_category,
        expense_category_handler::delete_expense_category,
        dunning_handler::list_dunning_levels,
        dunning_handler::update_dunning_level,
        dunning_handler::get_invoice_dunning_history,
        dunning_handler::send_reminder,
        dunning_handler::run_dunning,
        invoice_handler::create_invoice_from_time_entries,
        bank_transaction_handler::list_bank_transactions,
        bank_transaction_handler::import_camt053,
        bank_transaction_handler::auto_match,
        bank_transaction_handler::manual_match,
        bank_transaction_handler::create_journal_from_tx,
        bank_transaction_handler::ignore_transaction,
        vat_rate_handler::list_vat_rates,
        vat_rate_handler::create_vat_rate,
        vat_rate_handler::update_vat_rate,
        vat_rate_handler::deactivate_vat_rate,
        currency_handler::list_currencies,
        currency_handler::create_currency,
        currency_handler::update_currency,
        activity_type_handler::list_activity_types,
        activity_type_handler::create_activity_type,
        activity_type_handler::update_activity_type,
        activity_type_handler::delete_activity_type,
        invoice_handler::record_payment,
        invoice_handler::list_payments,
        report_handler::create_vat_payment,
        report_handler::export_vat_xml,
        fixed_asset_handler::list_fixed_assets,
        fixed_asset_handler::get_fixed_asset,
        fixed_asset_handler::create_fixed_asset,
        fixed_asset_handler::update_fixed_asset,
        fixed_asset_handler::delete_fixed_asset,
        fixed_asset_handler::get_depreciation_schedule,
        fixed_asset_handler::run_depreciation,
        employee_handler::list_employees,
        employee_handler::get_employee,
        employee_handler::create_employee,
        employee_handler::update_employee,
        employee_handler::delete_employee,
        payroll_settings_handler::get_payroll_settings,
        payroll_settings_handler::update_payroll_settings,
        payroll_run_handler::list_payroll_runs,
        payroll_run_handler::get_payroll_run,
        payroll_run_handler::create_payroll_run,
        payroll_run_handler::calculate_payroll_run,
        payroll_run_handler::approve_payroll_run,
        payroll_run_handler::mark_payroll_run_paid,
        payroll_run_handler::delete_payroll_run,
        payroll_run_handler::download_payslip,
        payroll_run_handler::download_payslips_zip,
        salary_certificate_handler::list_salary_certificates,
        salary_certificate_handler::download_salary_certificate_pdf,
        salary_certificate_handler::download_salary_certificates_zip,
        payout_handler::list_payout_entries,
        payout_handler::generate_payouts,
        payout_handler::export_pain001,
        payout_handler::mark_payout_paid,
        payout_handler::mark_all_payouts_paid,
        project_handler::get_budget_analytics,
        time_entry_handler::transition_time_entry,
        project_sub_status_handler::list_project_sub_statuses,
        project_sub_status_handler::create_project_sub_status,
        project_sub_status_handler::update_project_sub_status,
        project_sub_status_handler::delete_project_sub_status,
        setup_handler::setup_status,
        setup_handler::setup_complete,
        setup_handler::get_branding,
        project_member_handler::list_project_members,
        project_member_handler::add_project_member,
        project_member_handler::update_project_member,
        project_member_handler::remove_project_member,
        project_activity_type_handler::list_project_activity_types,
        project_activity_type_handler::add_project_activity_type,
        project_activity_type_handler::update_project_activity_type,
        project_activity_type_handler::remove_project_activity_type,
    ),
    components(
        schemas(
            LoginRequest, RefreshRequest, TokenResponse, MeResponse, UpdateMyLanguageRequest, UpdateMyProfileRequest,
            AccountResponse, CreateAccountRequest, UpdateAccountRequest,
            AccountTreeNode,
            ContactResponse, CreateContactRequest, UpdateContactRequest,
            JournalEntryResponse, JournalLineResponse, JournalDetailResponse,
            CreateJournalEntryRequest, CreateJournalLineRequest,
            ProjectResponse, CreateProjectRequest, UpdateProjectRequest,
            TimeEntryResponse, CreateTimeEntryRequest, UpdateTimeEntryRequest,
            FiscalYearResponse, FiscalPeriodResponse, FiscalYearDetailResponse,
            CreateFiscalYearRequest, UpdateFiscalYearRequest,
            ExchangeRateResponse, CreateExchangeRateRequest,
            UpdateExchangeRateRequest,
            TrialBalanceRowResponse, BalanceSheetResponse, ProfitLossResponse,
            LedgerLineResponse, VatReportEntryResponse, VatReportResponse,
            DashboardStatsResponse, RecentEntryResponse,
            ImportJobResponse,
            CompanySettingsResponse, UpdateCompanySettingsRequest,
            BankAccountResponse, CreateBankAccountRequest, UpdateBankAccountRequest,
            TemplateResponse, CreateTemplateRequest, UpdateTemplateRequest,
            DocumentResponse, DocumentLineItemResponse, DocumentDetailResponse,
            CreateDocumentRequest, CreateDocumentLineRequest, ConvertDocumentRequest,
            RecurringInvoiceResponse, CreateRecurringInvoiceRequest,
            UpdateRecurringInvoiceRequest, RecurringInvoiceLineRequest,
            CreditNoteResponse, CreditNoteLineResponse, CreditNoteDetailResponse,
            CreateCreditNoteRequest, CreateCreditNoteLineRequest,
            MonthlyAmountResponse, InvoiceAgingBucketResponse,
            OutstandingContactResponse, OverviewMonthResponse, OverviewResponse,
            CashFlowReportResponse,
            CashFlowSectionResponse, CashFlowItemResponse,
            AgingBucketResponse,
            EmailTemplateResponse, UpdateEmailTemplateRequest,
            EmailTemplatePreviewResponse,
            ExpenseResponse, ExpenseDetailResponse,
            CreateExpenseRequest, PayExpenseRequest,
            ExpenseCategoryResponse, CreateExpenseCategoryRequest,
            UpdateExpenseCategoryRequest,
            ContactTagResponse, CreateContactTagRequest,
            ContactPersonResponse, CreateContactPersonRequest,
            UpdateContactPersonRequest,
            ProjectSummaryResponse,
            CreateInvoiceFromTimeEntriesRequest,
            DocumentSummaryResponse,
            DunningLevelResponse, UpdateDunningLevelRequest,
            DunningEntryResponse, SendReminderRequest, DunningRunResponse,
            BankTransactionResponse, ManualMatchRequest, CreateJournalFromTxRequest,
            AutoMatchResponse, ImportResponse,
            VatRateResponse, CreateVatRateRequest, UpdateVatRateRequest,
            CurrencyResponse, CreateCurrencyRequest, UpdateCurrencyRequest,
            ActivityTypeResponse, CreateActivityTypeRequest, UpdateActivityTypeRequest,
            InvoicePaymentResponse, RecordPaymentRequest,
            CreateVatPaymentRequest, VatPaymentResponse, ExportVatXmlRequest,
            FixedAssetResponse, CreateFixedAssetRequest, UpdateFixedAssetRequest,
            DepreciationEntryResponse, RunDepreciationRequest,
            EmployeeResponse, CreateEmployeeRequest, UpdateEmployeeRequest,
            PayrollSettingsResponse, UpdatePayrollSettingsRequest,
            PayrollRunResponse, PayrollRunLineResponse, PayrollRunDetailResponse,
            CreatePayrollRunRequest,
            PayoutEntryResponse, GeneratePayoutsRequest,
            LohnausweisData, EmployeeSummary,
            BudgetAnalyticsResponse, MemberBudgetRow, ActivityBudgetRow, WeeklyBudgetPoint,
            ProjectSubStatusResponse, CreateProjectSubStatusRequest, UpdateProjectSubStatusRequest,
            ProjectMemberResponse, CreateProjectMemberRequest, UpdateProjectMemberRequest,
            ProjectActivityTypeResponse, CreateProjectActivityTypeRequest, UpdateProjectActivityTypeRequest,
            TransitionTimeEntryRequest,
            SetupStatusResponse, SetupCompleteRequest, SetupCompleteResponse, BrandingResponse,
        )
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "accounts", description = "Chart of Accounts"),
        (name = "contacts", description = "Contact Management"),
        (name = "journal", description = "Journal Entries"),
        (name = "projects", description = "Projects"),
        (name = "time-entries", description = "Time Tracking"),
        (name = "fiscal-years", description = "Fiscal Years"),
        (name = "exchange-rates", description = "Exchange Rates"),
        (name = "reports", description = "Financial Reports"),
        (name = "dashboard", description = "Dashboard"),
        (name = "import", description = "Data Import"),
        (name = "settings", description = "Company Settings"),
        (name = "bank-accounts", description = "Bank Accounts"),
        (name = "templates", description = "Document Templates"),
        (name = "documents", description = "Documents (Quotes, Offers, SOWs, Contracts)"),
        (name = "recurring-invoices", description = "Recurring Invoices"),
        (name = "credit-notes", description = "Credit Notes / Gutschriften"),
        (name = "email-templates", description = "Email Templates"),
        (name = "expenses", description = "Expenses & Supplier Bills"),
        (name = "expense-categories", description = "Expense Categories"),
        (name = "contact-tags", description = "Contact Tags"),
        (name = "contact-persons", description = "Contact Persons"),
        (name = "dunning", description = "Payment Reminders / Dunning"),
        (name = "bank-transactions", description = "Bank Transactions & Reconciliation"),
        (name = "vat-rates", description = "VAT Rates"),
        (name = "currencies", description = "Currencies"),
        (name = "activity-types", description = "Activity Types"),
        (name = "fixed-assets", description = "Fixed Assets & Depreciation"),
        (name = "employees", description = "Employee Management"),
        (name = "payroll-settings", description = "Payroll Settings"),
        (name = "payroll-runs", description = "Payroll Runs & Calculation"),
        (name = "salary-certificates", description = "Annual Salary Certificates"),
        (name = "payout", description = "Payout Schedule & pain.001 Export"),
        (name = "project-members", description = "Project Team Members"),
        (name = "project-activity-types", description = "Project Activity Type Configuration"),
        (name = "project-sub-statuses", description = "Project Sub-Statuses"),
        (name = "setup", description = "First-Run Setup Wizard"),
    ),
    info(
        title = "Hope Accounting API",
        version = "0.1.0",
        description = "Swiss accounting system by Maravilla Labs"
    )
)]
pub struct ApiDoc;
