/// Returns (number, name, account_type) tuples for the chart of accounts.
pub fn chart_of_accounts() -> Vec<(i32, &'static str, &'static str)> {
    vec![
        (1000, "Kassenkonto", "asset"),
        (1020, "Bank UBS CHF", "asset"),
        (1021, "Bank EUR", "asset"),
        (1022, "UBS Switzerland AG", "asset"),
        (1029, "Bank", "asset"),
        (1090, "Transferkonto", "asset"),
        (1091, "Lohndurchlaufkonto", "asset"),
        (1100, "Forderungen Debitoren", "asset"),
        (1170, "Vorsteuer Material/Waren", "asset"),
        (1171, "Vorsteuer Investitionen", "asset"),
        (1183, "KK Unfallversicherung", "asset"),
        (1192, "Geleistete Anzahlungen", "asset"),
        (1300, "Bezahlter Aufwand Folgejahr", "asset"),
        (1521, "Informatik", "asset"),
        (2000, "Verbindlichkeiten Kreditoren", "liability"),
        (2030, "Erhaltene Anzahlungen", "liability"),
        (2200, "Geschuldete MWST", "liability"),
        (2201, "Abrechnungskonto MWST", "liability"),
        (2260, "KK Gesellschafter", "liability"),
        (2270, "KK Vorsorgeeinrichtung", "liability"),
        (2271, "KK AHV/IV/EO/ALV", "liability"),
        (2272, "KK FAK/VK", "liability"),
        (2273, "KK Unfallversicherung", "liability"),
        (2274, "KK Krankentaggeld", "liability"),
        (2300, "Noch nicht bezahlter Aufwand", "liability"),
        (2340, "Rückstellungen Steuern", "liability"),
        (2800, "Stammkapital", "equity"),
        (2970, "Gewinn/Verlustvortrag", "equity"),
        (2979, "Jahresgewinn/Jahresverlust", "equity"),
        (3200, "Bruttoerlöse Barverkäufe", "revenue"),
        (3201, "Bruttoerlöse Kreditverkäufe", "revenue"),
        (3400, "Bruttoerlöse Bargeschäft", "revenue"),
        (3401, "Bruttoerlöse Kreditgeschäft", "revenue"),
        (3680, "Sonstige Erlöse", "revenue"),
        (3800, "Skonti", "revenue"),
        (3809, "MWST Saldosteuersatz", "revenue"),
        (4060, "Rechtsberatung", "expense"),
        (4200, "Einkauf Handelsware", "expense"),
        (4400, "Einkauf Dienstleistung", "expense"),
        (4407, "Direkte Einkaufsspesen", "expense"),
        (4470, "Direkte Einkaufsspesen Dienstleistungen", "expense"),
        (4640, "Übriger Aufwand Dienstleistungen", "expense"),
        (4710, "Customer/Business Travel", "expense"),
        (4900, "Skonti", "expense"),
        (4906, "Kursdifferenzen", "expense"),
        (5000, "Löhne", "expense"),
        (5005, "Leistungen Sozialversicherungen", "expense"),
        (5700, "AHV/IV/EO/ALV", "expense"),
        (5710, "FAK", "expense"),
        (5720, "BVG", "expense"),
        (5730, "UVG", "expense"),
        (5740, "KTG", "expense"),
        (5820, "Reisespesen", "expense"),
        (5832, "Pauschalspesen", "expense"),
        (6000, "Mietzins", "expense"),
        (6100, "URE Maschinen", "expense"),
        (6220, "Versicherungen", "expense"),
        (6300, "Sachversicherungen", "expense"),
        (6360, "Abgaben/Gebühren", "expense"),
        (6500, "Büromaterial", "expense"),
        (6510, "Telefon", "expense"),
        (6520, "Beiträge", "expense"),
        (6530, "Buchführung", "expense"),
        (6531, "Unternehmensberatung", "expense"),
        (6532, "Rechts/Steuerberatung", "expense"),
        (6550, "Gründungsaufwand", "expense"),
        (6551, "Inkasso", "expense"),
        (6559, "Sonstiger Verwaltungsaufwand", "expense"),
        (6570, "Leasing Hard/Software", "expense"),
        (6822, "Abschreibungen Informatik", "expense"),
        (6900, "Bankkreditzins", "expense"),
        (6903, "Verzugszins", "expense"),
        (6940, "Bankspesen", "expense"),
        (6945, "Rundungsdifferenz", "expense"),
        (6949, "Währungsverluste", "expense"),
        (6999, "Währungsgewinne", "expense"),
        (8510, "Ausserordentlicher Aufwand", "expense"),
        (8709, "Periodenfremder Aufwand", "expense"),
        (8719, "Periodenfremder Ertrag", "expense"),
        (8900, "Steuern", "expense"),
        (9100, "Eröffnungsbilanz", "system"),
        (9200, "Jahresgewinn/Jahresverlust", "system"),
        (9901, "Saldoübernahme", "system"),
    ]
}

/// Returns (id, code, name, rate) for VAT rates.
pub fn vat_rates() -> Vec<(&'static str, &'static str, &'static str, f64)> {
    vec![
        ("vat-81", "UO81", "Standard 8.1%", 8.1),
        ("vat-77", "UO77", "Previous Standard 7.7%", 7.7),
        ("vat-26", "US26", "Reduced 2.6%", 2.6),
        ("vat-38", "US38", "Accommodation 3.8%", 3.8),
    ]
}

/// Returns (id, name) for activity types.
pub fn activity_types() -> Vec<(&'static str, &'static str)> {
    vec![
        ("act-admin", "Administration"),
        ("act-general", "Allgemein"),
        ("act-ba", "Business Analyst (Standard)"),
        ("act-meeting", "Meeting"),
        ("act-pm", "Projekt Management"),
        ("act-sa", "Software Architecture"),
        ("act-dev", "Software Development (General)"),
        ("act-sysarch", "System Architecture"),
        ("act-doc", "Technical Documentation"),
        ("act-travel", "Travel"),
        ("act-impl", "Umsetzung"),
    ]
}
