use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Serialize, ToSchema)]
pub struct ContactResponse {
    pub id: String,
    pub contact_type: String,
    pub category: Option<String>,
    pub industry: Option<String>,
    pub name1: String,
    pub name2: Option<String>,
    pub salutation: Option<String>,
    pub title: Option<String>,
    pub email: Option<String>,
    pub email2: Option<String>,
    pub phone: Option<String>,
    pub phone2: Option<String>,
    pub mobile: Option<String>,
    pub fax: Option<String>,
    pub address: Option<String>,
    pub postal_code: Option<String>,
    pub city: Option<String>,
    pub country: Option<String>,
    pub website: Option<String>,
    pub vat_number: Option<String>,
    pub language: Option<String>,
    pub notes: Option<String>,
    pub birthday: Option<String>,
    pub employee_count: Option<i32>,
    pub trade_register_number: Option<String>,
    pub salutation_form: Option<String>,
    pub customer_number: Option<String>,
    pub vat_mode: String,
    pub is_active: bool,
}

#[derive(Debug, Deserialize, ToSchema)]
pub struct CreateContactRequest {
    pub contact_type: String,
    pub name1: String,
    pub name2: Option<String>,
    pub salutation: Option<String>,
    pub title: Option<String>,
    pub email: Option<String>,
    pub email2: Option<String>,
    pub phone: Option<String>,
    pub phone2: Option<String>,
    pub mobile: Option<String>,
    pub fax: Option<String>,
    pub address: Option<String>,
    pub postal_code: Option<String>,
    pub city: Option<String>,
    pub country: Option<String>,
    pub industry: Option<String>,
    pub language: Option<String>,
    pub notes: Option<String>,
    pub birthday: Option<String>,
    pub employee_count: Option<i32>,
    pub trade_register_number: Option<String>,
    pub salutation_form: Option<String>,
    pub website: Option<String>,
    pub vat_number: Option<String>,
    pub customer_number: Option<String>,
    pub category: Option<String>,
    pub vat_mode: Option<String>,
}

#[derive(Debug, Deserialize, ToSchema)]
pub struct UpdateContactRequest {
    pub name1: Option<String>,
    pub contact_type: Option<String>,
    pub name2: Option<Option<String>>,
    pub salutation: Option<Option<String>>,
    pub title: Option<Option<String>>,
    pub email: Option<Option<String>>,
    pub email2: Option<Option<String>>,
    pub phone: Option<Option<String>>,
    pub phone2: Option<Option<String>>,
    pub mobile: Option<Option<String>>,
    pub fax: Option<Option<String>>,
    pub city: Option<Option<String>>,
    pub country: Option<Option<String>>,
    pub industry: Option<Option<String>>,
    pub language: Option<Option<String>>,
    pub notes: Option<Option<String>>,
    pub address: Option<Option<String>>,
    pub postal_code: Option<Option<String>>,
    pub website: Option<Option<String>>,
    pub vat_number: Option<Option<String>>,
    pub is_active: Option<bool>,
    pub birthday: Option<Option<String>>,
    pub employee_count: Option<Option<i32>>,
    pub trade_register_number: Option<Option<String>>,
    pub salutation_form: Option<Option<String>>,
    pub customer_number: Option<Option<String>>,
    pub category: Option<Option<String>>,
    pub vat_mode: Option<String>,
}

impl From<konto_db::entities::contact::Model> for ContactResponse {
    fn from(m: konto_db::entities::contact::Model) -> Self {
        Self {
            id: m.id,
            contact_type: m.contact_type,
            category: m.category,
            industry: m.industry,
            name1: m.name1,
            name2: m.name2,
            salutation: m.salutation,
            title: m.title,
            email: m.email,
            email2: m.email2,
            phone: m.phone,
            phone2: m.phone2,
            mobile: m.mobile,
            fax: m.fax,
            address: m.address,
            postal_code: m.postal_code,
            city: m.city,
            country: m.country,
            website: m.website,
            vat_number: m.vat_number,
            language: m.language,
            notes: m.notes,
            birthday: m.birthday.map(|d| d.format("%Y-%m-%d").to_string()),
            employee_count: m.employee_count,
            trade_register_number: m.trade_register_number,
            salutation_form: m.salutation_form,
            customer_number: m.customer_number,
            vat_mode: m.vat_mode,
            is_active: m.is_active,
        }
    }
}
